spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuisenio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true
    initialization-mode: always
  sql:
    init:
      continue-on-error: true
