spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuisenio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
file:
  uploadDir: ./uploads
  #debug: true
#logging:
  #level:
    #root: DEBUG
jwt:
  secret: 0nD6Am6uV7MJnkB6uShOXo2xXkvySAkToMeIM0W8eNw=
  expiration: 36000000


